### ISSUE TITLE
admin login is problematic

### ISSUE THREAD

**Issue by barisakpunar** [annytab/a-webshop#1]
I Can't enter the admin interface.it always redirect to login page

**Comment by fredrik-stigsson** [comment]
Hi,

do you login with Master as the username (only username and no password). What is your setup, do you use Visual Studio or have you uploaded the code to a webserver? 

Have you created an empty database and have you set the ConnectionString to this database?

Do you allow cookies in your web browser?

Do you have https enabled? I am going to make an update to the code so that a HTTPS redirect only are made if you set the REDIRECT-HTTPS setting to true.

**Comment by barisakpunar** [comment]
The problem is solved with the new commits. Thank you.

**Comment by fredrik-stigsson** [comment]
Ok, that is good. You are welcome.
